routes/web.php
<?php

use App\Models\Film;
use App\Models\Genre;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    $films = Film::all();
    $genre = Genre::all();

    return view('welcome', ['films' => $films, 'genres' => $genre]);
});

Auth::routes();



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/single/movie/{film}', [App\Http\Controllers\FilmController::class, 'single'])->name('single');

Route::resource('/purchase', App\Http\Controllers\TransactionController::class);


Route::resource('/film', App\Http\Controllers\FilmController::class);
Route::get('/films', [App\Http\Controllers\FilmController::class, 'films'])->name('film.manage');
Route::post('/search/films', [App\Http\Controllers\FilmController::class, 'search'])->name('purchase-search');

Route::post('/search/customer', [App\Http\Controllers\Auth\UserController::class, 'search'])->name('customer-search');
Route::get('/search/customer', [App\Http\Controllers\Auth\UserController::class, 'search'])->name('customer-search');
Route::get('/customers', [App\Http\Controllers\Auth\UserController::class, 'index'])->name('customers');
Route::get('/history', [App\Http\Controllers\TransactionController::class, 'index'])->name('history');
Route::get('/profile/{user}', [App\Http\Controllers\Auth\UserController::class, 'profile'])->name('profile');
Route::post('/update/profile/{user}', [App\Http\Controllers\Auth\UserController::class, 'update'])->name('profile.update');
Route::post('/profile/{user}', [App\Http\Controllers\Auth\UserController::class, 'password'])->name('password');

resources/views/create_film.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create Film') }}</div>
                <div class="card-body">
                    @if (session('success'))
                    <div class="row">
                        <div class="col-12 p-3 mb-5 alert alert-success" role="alert" >
                            {{ session('success') }}
                        </div>
                    </div>
                 @endif
                    <form method="POST" action="{{ route('film.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" required autocomplete="title" autofocus>

                                @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

                            <div class="col-md-6">
                                <input id="description" type="text" class="form-control @error('description') is-invalid @enderror" name="description" value="{{ old('description') }}" required autocomplete="description">

                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="dob" class="col-md-4 col-form-label text-md-right">{{ __('Genre') }}</label>

                            <div class="col-md-6">

                                <select name="genre_id" class="d-inline mr-3 form-control">
                                    @foreach ( $genres as $genre)
                                    <option value="{{ $genre->id }} "> {{ $genre->name }} </option>
                                    @endforeach
                                </select>

                                @error('genre')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="rating" class="col-md-4 col-form-label text-md-right">{{ __('Rating') }}</label>

                            <div class="col-md-6">

                                <select name="rating" class="d-inline mr-3 form-control">
                                   
                                    <option value="{{ 1 }} "> 1 </option>
                                    <option value="{{ 2 }} "> 2 </option>
                                    <option value="{{ 3 }} "> 3 </option>
                                    <option value="{{ 4 }} "> 4 </option>
                                    <option value="{{ 5 }} "> 5 </option>
                                </select>

                                @error('rating')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="year" class="col-md-4 col-form-label text-md-right">{{ __('Year') }}</label>

                            <div class="col-md-6">
                                <input id="year" type="number" class="form-control @error('year') is-invalid @enderror" name="year" value="{{ old('year') }}" required autocomplete="year">
                                @error('year')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        

                        <div class="form-group row">
                            <label for="cost" class="col-md-4 col-form-label text-md-right">{{ __('Cost') }}</label>

                            <div class="col-md-6">
                                <input id="cost" type="number" class="form-control @error('cost') is-invalid @enderror" name="cost" value="{{ old('cost') }}" required autocomplete="cost">
                                @error('cost')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="image" class="col-md-4 col-form-label text-md-right">{{ __('Image') }}</label>

                            <div class="col-md-6">
                                <input id="image" type="file" class="form-control @error('image') is-invalid @enderror" name="image" required autocomplete="new-image">

                                @error('image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Create') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/customers.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12 p-3 mb-5" style="background: white">

            <form Method="POST" action="{{ route('customer-search') }}">
                @csrf
            <label>Name</label>
            <input type="text" class="d-inline form-control col-3"  name="name"/>
            <label class="ml-4">Age</label>
            <input type="text" class="d-inline  form-control col-3" name="age" placeholder="equals or below"/>
            <input type="submit"  class="btn btn-primary d-inline ml-2"  value="Search" name=""/>
        </form>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Customers') }}</div>

                <div class="card-body">

                    <table class="table table-hover">

                            <thead>
                              <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">Email</th>
                                <th scope="col">Address</th>
                                <th scope="col">DOB</th>
                                <th scope="col">Date</th>
                                <th scope="col">Movies Purchased</th>
                              </tr>
                            </thead>
                            <tbody>
                                @foreach ( $users as $user )
                                <tr>
                                    <th scope="row">{{ $loop->iteration }}</th>
                                    <td>{{ $user->name}}</td>
                                    <td>{{$user->email}}</td>
                                    <td>{{$user->address}}</td>
                                    <td>{{$user->dob}}</td>
                                    <td>{{$user->created_at}}</td>
                                    <td> {{$user->transactions->count()}} </td>
                                  </tr>
                                @endforeach
                            </tbody>

                      </table>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/history.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Purchase History') }}</div>

                <div class="card-body">

                    <table class="table table-hover">

                            <thead>
                              <tr>
                                <th scope="col">#</th>
                                <th scope="col">FIlm Title</th>
                                <th scope="col">FIlm Genre</th>
                                <th scope="col">Cost</th>
                                <th scope="col">Date</th>
                              </tr>
                            </thead>
                            <tbody>
                                @foreach ( $transactions as $transaction )
                                <tr>
                                    <th scope="row">{{ $loop->iteration }}</th>
                                    <td>{{ $transaction->film->title}}</td>
                                    <td>{{$transaction->film->genre->name}}</td>
                                    <td>{{$transaction->film->cost}}</td>
                                    <td>{{$transaction->created_at}}</td>
                                  </tr>
                                @endforeach
                            </tbody>

                      </table>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @can("isAdmin")
        <div class="row justify-content-center  ">
            <div class="col-4 p-3" style="background: white">
                <h4>Current Month Sales</h4>
                <h2>{{ $current_month }}</h2>
            </div>
            <div class="col-4 p-3" style="background: white">
                <h4>Last Month Sales</h4>
                <h2>{{ $last_month }}</h2>
            </div>

            <div class="col-4 p-4" style="background: white" >
                <h4>Total Purchase</h4>
                <h2>{{ $total_purchase }}</h2>
            </div>
        </div>
    @endcan
    <div class="row mt-5">

        @foreach ($films as $film )
        <div class="col-sm-3">
            <div class="card" >
                <img src="/images/{{ $film->image }}" class="card-img-top" style="height: 300px;" alt="{{ $film->title }}">
                <div class="card-body">
                <form method="POST" action="{{ route('purchase.store') }}">
                    @csrf
                <h5 class="card-title">{{ $film->title }}</h5>
                <p class="card-text">{{ $film->description }}</p>
                <input type="hidden" name="movie_id" value="{{ $film->id }}" />
                <input type="hidden" name="title" value="{{ $film->title }}" />
                <input type="submit" class="btn btn-primary" value="Purchase">
                </form>
                </div>
            </div>
        </div>
        @endforeach

    </div>
</div>
@endsection

resources/views/manage.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12 p-3 mb-5" style="background: white">
            <a href="/film/create" class="btn btn-primary" >Create Film</a>
        </div>
    </div>

    @if (session('success'))
        <div class="row">
            <div class="col-12 p-3 mb-5 alert alert-success" role="alert" >
                {{ session('success') }}
            </div>
        </div>
    @endif

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Purchase History') }}</div>

                <div class="card-body">

                    <table class="table table-hover">

                            <thead>
                              <tr>
                                <th scope="col">#</th>
                                <th scope="col">FIlm Title</th>
                                <th scope="col">FIlm Genre</th>
                                <th scope="col">Rating</th>
                                <th scope="col">Year</th>
                                <th scope="col">FIlm Image</th>
                                <th scope="col">Cost</th>
                                <th scope="col">Date</th>
                                <th scope="col">Action</th>
                              </tr>
                            </thead>
                            <tbody>

                                @forelse ( $films as $film )

                                <tr>
                                    <th scope="row">{{ $loop->iteration }}</th>
                                    <td>{{ $film->title}} - {{ $film->description}}</td>
                                    <td>{{$film->genre->name}}</td>
                                    <td>{{$film->rating}}</td>
                                    <td>{{$film->year}}</td>
                                    <td><img src="/images/{{$film->image}}"  style="max-width: 100px"/> </td>
                                    <td>{{$film->cost}}</td>
                                    <td>{{$film->created_at}}</td>
                                    <td>
                                        <form method="POST" action="{{ route('film.destroy', $film->id ) }}">
                                            @method('DELETE')
                                            @csrf
                                            <input type="submit" value="Delete" class="btn btn-danger mb-3">
                                        </form>

                                        <a href="{{ route('film.edit', $film->id ) }}" class="btn btn-success">Edit</a>

                                    </td>
                                  </tr>
                                  @empty
                                    <p>No Film Inserted</p>
                                @endforelse
                            </tbody>

                      </table>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/purchase.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12 p-3 mb-5" style="background: white">

            <form Method="POST" action="{{ route('purchase-search') }}">
                @csrf
            <label>Genre</label>
            <select name="genre" class="d-inline form-control col-3 mr-3">
                <option value=""> ---- Select Genre ---- </option>
                @foreach ( $genres as $genre)
                <option value="{{ $genre->id }} "> {{ $genre->name }} </option>
                @endforeach
            </select>
            <label>Title</label>
            <input type="text" class="d-inline form-control col-3" name="title"/>

            <input type="submit"  class="btn btn-primary d-inline"  value="Search" name=""/>
        </form>
        </div>
    </div>

    @if (session('success'))
        <div class="row">
            <div class="col-12 p-3 mb-5 alert alert-success" role="alert" >
                {{ session('success') }}
            </div>
        </div>
    @endif
    <div class="row ">

        @foreach ($films as $film )
        <div class="col-sm-3">
            <div class="card" >
                <img src="/images/{{ $film->image }}" class="card-img-top" style="height: 300px;" alt="{{ $film->title }}">
                <div class="card-body">
                <h5 class="card-title">{{ $film->title }}</h5>
                <p class="card-text">{{ $film->description }}</p>
                <a href="{{ route('single', $film->id) }}" class="btn btn-primary">Purchase</a>
                </div>
            </div>
        </div>
        @endforeach

    </div>
</div>
@endsection

resources/views/single_movie.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="/images/{{ $film->image }}" class="card-img-top" style="height: 600px;" alt="{{ $film->title }}">
        </div>
        <div class="col-md-6">

            <h1>{{ $film->title }}</h1>
            <p>{{ $film->description }}</p>
            <h3>Price: {{ $film->cost }}</h3>
            @auth
            <form method="POST" action="{{ route('purchase.store') }}">
                @csrf
            <div class="row mt-5">
                <div class="col-xs-12 col-md-12 mt-5">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">
                                Payment Details
                            </h3>
                        </div>
                        <div class="panel-body">
                            <form role="form">
                            <div class="form-group">
                                <label for="cardNumber">
                                    CARD NUMBER</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" id="cardNumber" placeholder="Valid Card Number"
                                        required autofocus />
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-7 col-md-7">
                                    <div class="form-group">
                                        <label for="expityMonth">
                                            EXPIRY DATE</label>
                                        <div class="col-xs-6 col-lg-6 pl-ziro">
                                            <input type="text" class="form-control" id="expityMonth" placeholder="MM" required />
                                        </div>
                                        <div class="col-xs-6 col-lg-6 pl-ziro">
                                            <input type="text" class="form-control" id="expityYear" placeholder="YY" required /></div>
                                    </div>
                                </div>
                                <div class="col-xs-5 col-md-5 pull-right">
                                    <div class="form-group">
                                        <label for="cvCode">
                                            CV CODE</label>
                                        <input type="password" class="form-control" id="cvCode" placeholder="CV" required />
                                    </div>
                                </div>
                            </div>
                            </form>
                        </div>
                    </div>
                    <br/>
                    <input type="hidden" name="movie_id" value="{{ $film->id }}" />
                    <input type="hidden" name="title" value="{{ $film->title }}" />
                    <input type="submit" class="btn btn-success btn-lg btn-block" value="Purchase">

                </div>
            </div>
        </form>

            @else
            <h2>Please Login into your account or create a new one <a href="/login" class="btn btn-primary"> Login </a> </h2>
            @endauth
        </div>
    </div>
</div>
@endsection

resources/views/update_film.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Update {{ $film->title }}</div>
                <div class="card-body">
                    @if (session('success'))
                    <div class="row">
                        <div class="col-12 p-3 mb-5 alert alert-success" role="alert" >
                            {{ session('success') }}
                        </div>
                    </div>
                 @endif
                    <form method="POST" action="{{ route('film.update', $film->id) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ $film->title }}" required autocomplete="title" autofocus>

                                @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

                            <div class="col-md-6">
                                <input id="description" type="text" class="form-control @error('description') is-invalid @enderror" name="description" value="{{ $film->description }}" required autocomplete="description">

                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="dob" class="col-md-4 col-form-label text-md-right">{{ __('Genre') }}</label>

                            <div class="col-md-6">

                                <select name="genre_id" class="d-inline mr-3 form-control">
                                    @foreach ( $genres as $genre)
                                    <option value="{{ $genre->id }} "> {{ $genre->name }} </option>
                                    @endforeach
                                </select>

                                @error('genre')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="cost" class="col-md-4 col-form-label text-md-right">{{ __('Cost') }}</label>

                            <div class="col-md-6">
                                <input id="cost" type="number" class="form-control @error('cost') is-invalid @enderror" name="cost" value="{{ $film->cost }}" required autocomplete="cost">
                                @error('cost')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="rating" class="col-md-4 col-form-label text-md-right">{{ __('Rating') }}</label>

                            <div class="col-md-6">

                                <select name="rating" class="d-inline mr-3 form-control">
                                   
                                    <option value="{{ 1 }} "> 1 </option>
                                    <option value="{{ 2 }} "> 2 </option>
                                    <option value="{{ 3 }} "> 3 </option>
                                    <option value="{{ 4 }} "> 4 </option>
                                    <option value="{{ 5 }} "> 5 </option>
                                </select>

                                @error('rating')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="year" class="col-md-4 col-form-label text-md-right">{{ __('Year') }}</label>

                            <div class="col-md-6">
                                <input id="year" type="number" class="form-control @error('year') is-invalid @enderror" name="year" value="{{ old('year') }}" required autocomplete="year">
                                @error('year')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="image" class="col-md-4 col-form-label text-md-right">{{ __('Image') }}</label>

                            <div class="col-md-6">
                                <input id="image" type="file" class="form-control @error('image') is-invalid @enderror" name="image"  autocomplete="new-image">

                                @error('image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Update') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection